# -*- coding: utf-8 -*-
"""0.클래스.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xrTsvzFo0qn9zW3xfBdOreTJ6bXCjd_V

# 개요

- 개발 방식
  - 절차 지향 프로그래밍
    - c, c++, java, python 등
    - 절차 : 타입, 자료구조, 조건/제어/반복문
    - 코드의 재사용성이 어려움
  - 함수 지향 프로그래밍
    - c, c++, java, python 등
    - 절차 + 함수
    - 코드의 재사용성이 상승함
  - 객체 지향 프로그래밍
    - c++, java, python 등
    - 절차 + 함수 + 클래스
    - 클래스는 상속성, 다형성, 은닉성 3가지 특성이 있어야 함

# 개념

- entity(개체)
  - 이 세상에 존재하는 유무형의 모든 것
  - 프로그래밍 세상에 entity를 표형하기 위해서는 표현도구(class)가 필요
- class
  - entity를 표현하기 위한 도구이며 문법이 존재함
  - 클래스 작성 -> 클래스 실행 -> 글래스 생성자를 호출 -> 객체가 클래스의 모습을 본딴 형태로 메모리에 상주하게 됨
  - 여러개 만들 수 있음
- object(객체)
  - 클래스가 작동하면 메모리에 할당(주소가 존재)됨
  - 특정 변수가 그 객체를 받아주면 그 변수를 객체라고 함(정확하게는 변수가 그 객체의 주소를 가리킨다는 의미임)
  - 파이썬의 모든 것은 객체
- Object : (이미 만들어져 있거나 내가 만든)모든 클래스의 부모 클래스임
"""